# Generated by Django 4.2 on 2025-12-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('alumno', models.ForeignKey(db_column='alumno_rut', on_delete=django.db.models.deletion.CASCADE, to='AppPrueba.alumno')),
                ('curso', models.ForeignKey(db_column='curso_codigo', on_delete=django.db.models.deletion.CASCADE, to='AppPrueba.curso')),
                ('sucursal', models.ForeignKey(db_column='sucursal_codigo', on_delete=django.db.models.deletion.CASCADE, to='AppPrueba.sucursal')),
            ],
        ),
    ]
